version: '3.7'

services:
  postgres:
    image: postgres:14.12-bullseye
    restart: unless-stopped
    volumes:
      - 'pg_data:/var/lib/postgresql/data:rw'
      - './scripts/docker-init-db.sh:/docker-entrypoint-initdb.d/docker-init-db.sh'
    ports:
      - 65432:5432
    environment:
      POSTGRES_USER: scorebrawl
      POSTGRES_PASSWORD: scorebrawl
      POSTGRES_DB: scorebrawl
      POSTGRES_MULTIPLE_DATABASES: scorebrawl,scorebrawl-e2e
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d scorebrawl -U scorebrawl']
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pg_data:
    name: scorebrawl-local-pg-data
    labels:
      origin: scorebrawl-local
